export const metadata = { title: "Conditions générales — BRIF" };

export default function ConditionsGenerales() {
 return <main className="page-shell"><div className="panel" style={{maxWidth:820,margin:"2rem auto"}}>
  <p className="eyebrow">BRIF</p><h1>Conditions générales de vente et d’utilisation</h1>
  <p>Version du 22 septembre 2026. BRIF est réservé aux professionnels.</p>
  <h2>1. Service</h2><p>BRIF permet à un artisan de recevoir, organiser et suivre les demandes transmises par ses propres clients. BRIF ne garantit ni l’apport de nouveaux clients, ni un volume de demandes, ni la conclusion d’un devis ou d’un chantier.</p>
  <h2>2. Prix</h2><p>Abonnement mensuel : 39 € par mois. Abonnement annuel : 390 € par an. Aucun frais d’installation. BRIF bénéficie actuellement de la franchise en base de TVA ; les prix facturés ne comportent donc pas de TVA.</p>
  <h2>3. Paiement</h2><p>Le paiement de l’abonnement est effectué d’avance par voie électronique. L’accès payant n’est activé qu’après confirmation du paiement. En cas d’échec de paiement, BRIF peut suspendre l’accès après information du client.</p>
  <p>En cas de retard de paiement entre professionnels, les pénalités prévues par le Code de commerce sont exigibles ainsi que l’indemnité forfaitaire légale de 40 € pour frais de recouvrement, lorsqu’elle est applicable.</p>
  <h2>4. Durée et résiliation</h2><p>L’offre mensuelle est sans engagement de durée et peut être résiliée à tout moment ; l’accès reste disponible jusqu’à la fin de la période mensuelle déjà payée. L’offre annuelle est payée d’avance ; une résiliation arrête son renouvellement et l’accès reste disponible jusqu’à l’échéance annuelle déjà payée. La période annuelle commencée n’est pas remboursée, sauf obligation légale contraire ou manquement imputable à BRIF justifiant un remboursement.</p>
  <h2>5. Données et rôle de l’artisan</h2><p>L’artisan demeure responsable des finalités pour lesquelles il collecte et utilise les données de ses clients. BRIF traite techniquement ces données pour son compte dans le cadre du service. BRIF n’utilise pas les données des clients de l’artisan pour sa propre prospection.</p>
  <h2>6. Protection des données et sous-traitance</h2><p>Pour les données que l’artisan confie à BRIF dans le cadre des demandes de ses clients, l’artisan agit comme responsable du traitement et BRIF comme sous-traitant. Le traitement a pour objet la collecte, l’hébergement, l’organisation, la consultation, la transmission et la suppression des demandes pendant la durée du service. Les personnes concernées sont les clients et prospects de l’artisan. Les catégories de données peuvent comprendre l’identité, les coordonnées, la commune, la description de la demande, l’urgence, les disponibilités et les photographies éventuellement transmises.</p><p>BRIF traite ces données uniquement pour fournir le service et selon les instructions documentées de l’artisan ; veille à la confidentialité des personnes autorisées à y accéder ; met en œuvre des mesures techniques et organisationnelles appropriées ; assiste l’artisan, dans la mesure du possible, pour l’exercice des droits des personnes, la sécurité et la gestion des violations de données ; met à disposition les informations raisonnablement nécessaires pour démontrer le respect de ces obligations ; et restitue ou supprime les données en fin de prestation, sauf obligation légale de conservation.</p><p>L’artisan autorise BRIF à recourir aux sous-traitants ultérieurs nécessaires au fonctionnement du service, notamment pour l’hébergement, la base de données, le stockage, l’envoi de messages et le paiement. BRIF demeure responsable de leur encadrement contractuel dans les conditions prévues par la réglementation applicable et informe le client des changements substantiels concernant ces prestataires.</p>
  <h2>7. Export et suppression</h2><p>L’artisan doit pouvoir récupérer ses demandes dans un format exploitable et supprimer les demandes qui ne sont plus nécessaires. À la fin de la relation contractuelle, les données confiées à BRIF sont restituées ou supprimées selon la procédure de sortie et les obligations légales applicables.</p>
  <h2>8. Cessation de BRIF</h2><p>Si l’éditeur décide de cesser définitivement l’exploitation de BRIF, les clients actifs seront informés avec un préavis raisonnable. BRIF organisera l’export complet des données propres à chaque client et fournira une procédure de migration vers une installation autonome permettant la continuité de l’outil sans abonnement auprès de l’éditeur.</p>
  <h2>9. Disponibilité et force majeure</h2><p>BRIF met en œuvre des moyens raisonnables pour assurer la disponibilité du service. Une interruption liée à un événement extérieur échappant au contrôle de l’éditeur et répondant aux conditions légales de la force majeure ne constitue pas une décision volontaire de cessation de BRIF.</p>
  <h2>10. Responsabilité</h2><p>L’artisan reste responsable de ses réponses, devis, interventions et relations avec ses propres clients. BRIF est un outil d’organisation des demandes et ne se substitue pas au professionnel.</p>
  <h2>11. Contact</h2><p>Contact : ludodulac@gmail.com.</p>
  <p><a href="/">Retour à BRIF</a></p>
 </div></main>;
}
