export const metadata = { title: "Confidentialité — BRIF" };

export default function Confidentialite() {
 return <main className="page-shell"><div className="panel" style={{maxWidth:820,margin:"2rem auto"}}>
  <p className="eyebrow">BRIF</p><h1>Confidentialité et données personnelles</h1>
  <p>Version du 22 septembre 2026.</p>
  <h2>Qui traite les données ?</h2><p>Pour les informations nécessaires à la gestion de l’abonnement BRIF, Ludovic Nicolas DULAC EI est responsable du traitement. Pour les demandes envoyées à un artisan par ses propres clients, l’artisan détermine l’usage de ces informations et BRIF intervient comme prestataire technique pour son compte.</p>
  <h2>Données traitées</h2><p>BRIF peut traiter les coordonnées de l’artisan et, pour une demande client, le nom, le téléphone, l’e-mail lorsqu’il est fourni, la commune, la catégorie et la description de la demande, son niveau d’urgence, les disponibilités et jusqu’à trois photographies.</p>
  <h2>Pourquoi ?</h2><p>Ces données servent à fournir le service, transmettre et présenter les demandes à l’artisan, sécuriser les comptes, gérer l’abonnement et assurer le support. Les données des clients des artisans ne sont pas revendues et ne sont pas utilisées par BRIF pour leur adresser de la prospection.</p>
  <h2>Conservation</h2><p>Les données ne sont conservées que pendant la durée nécessaire aux finalités pour lesquelles elles sont traitées et aux obligations légales applicables. Les demandes clients restent sous le contrôle de l’artisan, qui peut les supprimer lorsqu’elles ne sont plus nécessaires à son suivi. À la fin du service, elles sont restituées ou supprimées conformément aux conditions contractuelles et aux obligations légales applicables.</p>
  <h2>Prestataires techniques</h2><p>BRIF s’appuie sur des prestataires nécessaires au fonctionnement du service, notamment Vercel pour l’hébergement de l’application et Supabase pour la base de données et le stockage. BRIF utilise Stripe comme prestataire de paiement ; Stripe traite les données nécessaires au paiement et à la gestion de l’abonnement. Les éventuels prestataires d’envoi de messages sont également susceptibles de traiter les seules données nécessaires à leur mission. Lorsque des données sont susceptibles d’être traitées hors de l’Espace économique européen, BRIF s’appuie sur les mécanismes de protection prévus par la réglementation applicable et les engagements contractuels des prestataires concernés.</p>
  <h2>Sécurité</h2><p>BRIF limite l’accès aux données aux comptes autorisés et met en œuvre des mesures techniques destinées à empêcher les accès non autorisés, pertes ou divulgations. Les informations de paiement bancaire ne sont pas destinées à être enregistrées directement dans la base BRIF ; elles sont traitées par le prestataire de paiement.</p>
  <h2>Vos droits</h2><p>Pour les données liées au compte BRIF, vous pouvez demander, selon les conditions prévues par le RGPD, l’accès, la rectification, l’effacement, la limitation, l’opposition ou la portabilité de vos données en écrivant à ludodulac@gmail.com. Pour une demande envoyée à un artisan, la personne concernée doit en priorité s’adresser à l’artisan responsable de sa relation client ; BRIF l’assiste lorsque cela est nécessaire. Toute personne concernée peut également introduire une réclamation auprès de la CNIL.</p>
  <p><a href="/">Retour à BRIF</a></p>
 </div></main>;
}
